### PR TITLE
Update ClientTable.tsx

### LINKED ISSUE #3339: Fix incompatible type in ClientTable
### Share your bug report, feature request, or comment.

```
./components/admin/ClientTable.tsx:44:13
Type error: Type 'Key' is not assignable to type 'string | number | readonly string[]'.
  Type 'bigint' is not assignable to type 'string | number | readonly string[]'.

  42 |           <Input
  43 |             placeholder="Search display names..."
> 44 |             value={selectedKeys[0]}
     |             ^
  45 |             onChange={e => {
  46 |               setSelectedKeys(e.target.value ? [e.target.value] : []);
  47 |               confirm({ closeDropdown: false });
```

### PR DESCRIPTION
**Pull request by vishal-sharma-369**
solves: #3339

## Changes

changed   owncast/web/components/admin/ClientTable.tsx line 44 `value={selectedKeys[0]})` to `value={selectedKeys[0].toString()} // Convert selectedKeys[0] to string
` as the value attribute expects a value of type `string | number | readonly string[]` but previously it was assigned bigint.

### CODE REVIEW

**Comment by gabek** [comment]
Thanks for putting up this change! Looks like there's some whitespace formatting that the build is unhappy with, but other than that it looks good!

**Comment by vishal-sharma-369** [comment]
Fixed the indentation errors.

**Comment by gabek** [comment]
Awesome, thanks so much @vishal-sharma-369!

**Comment by vishal-sharma-369** [comment]
@gabek Sir please add hacktoberfest-accepted label to this pr

**Comment by gabek** [comment]
I've went ahead and added #hacktoberfest to the repo labels so each PR doesn't need to be individually labeled.

**Comment by vishal-sharma-369** [comment]
Thanks sir

**Pull request merged**
