### PR TITLE
Player loads path from Config

### PR DESCRIPTION
**Pull request by Ruxton**
Loads the HLS path from the config file

### CODE REVIEW

**Comment by gabek** [comment]
Hey there!  So there's some bad timing.  The web is going through an overhaul and there's a PR up for that work at #120.  Any changes to the web code will need to move in that direction.  I'm guessing there won't be too many changes to that refactor work from now on, so feel free to apply your updates to it and we can test out your change in the context of the new web code, or feel free to wait until that PR gets merged in.

**Comment by Ruxton** [comment]
@gabek yeah i noticed that and tried to keep the PR minimal for that reason. Holding onto P2P integration atm too, waiting for that rework to go through before sending it in.

**Comment by gabek** [comment]
The "private" path is used for local HLS storage and is not meant to be used for any public access.  If what you're doing is trying to surface the public web accessible path for files then a path in relation to `webroot` would need to be exposed.  We should maybe change `PublicHLSPath` to `PublicWebPath` and then `PublicHLSPath` would be a subdirectory relative to `PublicWebPath`, and that's what you'd expose in the API.

So an example if you customized the values:
PublicWebPath = `/home/user/owncast/public`
PublicHLSPath = `hls`

We could also just hard code the subdirectory to `hls` always, because customizing that doesn't really have much of a point, because what matters is where the webroot lives.
 
This would mean on the filesystem the public HLS files are in `/home/user/owncast/public/hls` and the config API would say that the files are in `hls`, because it's relative to `PublicHLSPath`.

**Comment by gingervitis** [comment]
@Ruxton sorry for the late reply here. I've recently merged in a ton of frontend changes.  A lot of files have also changed and or have been rearranged.
Can you apply your change requests to the updated code instead?

**Comment by gabek** [comment]
We've since simplified and removed the option for custom paths for now.  In the future we hope to circle back around and properly make all these paths customizable.

**Pull request closed without merging**
