### PR TITLE
Moved global modifier to fix cascading

### LINKED ISSUE #2964: Admin modals have incorrect title color
### Share your bug report, feature request, or comment.

It's hard to read. There must be a modal header text color override being set somewhere that should be removed.

image

### PR DESCRIPTION
**Pull request by LJPR**
moved :global from child .ant-modal selectors up to .modal to ensure access from  admin modals. Let me know if there's a better way to do this and I'll fix it! 

fixes #2964 :)

### CODE REVIEW

**Comment by gabek** [comment]
Looks like you accidentally commited changed package.json and package-lock.json files. Make sure to only commit files that you intend to.

**Comment by gabek** [comment]
The project won't build with this PR's changes. I get this error. Make sure tests pass when pushing up PR changes.

image

**Comment by gabek** [comment]
Hey there, it seems you still accidentally committed `package-lock.json` and `package.json`.

**Comment by LJPR** [comment]
> Hey there, it seems you still accidentally committed `package-lock.json` and `package.json`.

My apologies, I'll work on unbreaking this today. Thanks for your patience :)

**Comment by gabek** [comment]
It looks like you made changes to `web/components/ui/Modal/Modal.module.scss`, however, that file isn't used in the Admin at all.  Just to double check I went to the admin and opened a modal, and no changes were visible:

image

**Comment by gabek** [comment]
I happened to be in the admin styling files today so I went ahead and changed the style to fix this text color bug while I was in there. Hope you don't mind too much!

**Pull request closed without merging**
