### PR TITLE
Draft: refactor to common golang project layout

### PR DESCRIPTION
**Pull request by gravestench**
Hi, there! Cool project! Some of the nicest code I've seen!

Anyways, in this PR i have moved things around to adhere to a more [standard golang project layout](https://github.com/golang-standards/project-layout). This is mainly to reduce the noise in the repo root and to provide clarity.  For instance, moving the Owncast server `main.go` into `cmd/server` sets an example for including other build targets that would go along with Owncast that we may want in the repo (like a binary for streaming a test signal) but maybe not  in an actual release. Almost everything else has been moved into `internal/` as it is all intended to be used by Owncast and not imported to other projects.

________________________
* moved `main.go` build target into `cmd/server/`
* moved all owncast internal stuff into `internal/`
* moved build/docker scripts into `scripts/`
  * updated paths where necessary
* added installation script to `scripts/`
*  gone through all of the imports and cleaned up and organized them

### CODE REVIEW

**Comment by gabek** [comment]
Hi there, great to meet you! Thanks for wanting to be involved!

I must admit I'm a little overwhelmed by such a large change. And while it's been a long filed todo (#1522) it would be nice to discuss some goals and specifics before making pulling the trigger on such a big refactor.

While I don't doubt moving files around for a better layout be more correct, would you instead be interested in helping on some higher-level architecture and work toward some specifics in smaller chunks? I'd love to work with somebody who cares about this kind of thing, and it's clear you do!

**Comment by gravestench** [comment]
Yeah, totally. This only took about an hour or so and I was able to get everything compiling again. The embedded frontend build is also working.  I'm not sure why this PR shows conflicts, i rebased off of `development`.

**Comment by gravestench** [comment]
I can keep this PR open and we can discuss what we want to make sure works. I know it's a big refactor, but it's mainly because of all of the static frontend files.

**Comment by gravestench** [comment]
I'm wondering if all of the stuff inside of `web/_next/static` can be removed from the git cache and a rule be added to `.gitignore`

**Pull request closed without merging**
