### PR TITLE
fix the random placement of popup

### LINKED ISSUE #2358: Notify reminder popup can show up in odd places
### Share your bug report, feature request, or comment.

In this case it didn't even scroll with the rest of the page.

image

### PR DESCRIPTION
**Pull request by dorj222**
Currently, the Notify reminder popup may show up in some random locations. This PR fixes this problem, which is issue #2358.  In order to solve this problem, I added the container div that wraps the reminder popup and adds the position relative CSS property. Since [the Ant Design Popover](https://ant.design/components/popover) provides the floating property, this PR does not change the floating property of this reminder popup.

### CODE REVIEW

**Comment by gabek** [comment]
Oh weird, by scrolling I was able to throw it off. It stayed in the same place and didn't scroll with the page.

Peek 2022-12-12 07-49

**Comment by dorj222** [comment]
Thanks a lot for your feedback! I think I misunderstood this issue; I thought the reminder popup still should scroll with the page. I will fix this issue, and I sincerely apologize.

**Comment by dorj222** [comment]
So, the reminder popup should be fixed above the notify button and should not scroll with the page, am I correct?

**Comment by gabek** [comment]
The reminder popup should always stay next to the Notify button, and scroll with it if the page scrolls. I'm not sure why it was originally showing up not next to the Notify button (like in the original screenshot it rendered in a weird, random spot), or in what cases that would happen. But now it just needs to be able to scroll along with the button. Thanks for asking for clarification!

It seems to render properly in the Storybook story if that's useful at all: https://owncast.online/components/?path=%2Fdocs%2Fowncast-components-notify-reminder--active

Peek 2022-12-12 10-50


<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-components-notify-reminder--active">Webpack App</a></strong></div></blockquote>

**Comment by dorj222** [comment]
Because this branch and PR were so behind the webv2, I decided to create another branch and PR for issue #2358. [Here I created it](https://github.com/owncast/owncast/pull/2529).

**Pull request closed without merging**
