### PR TITLE
Fix path for image open meta tag #3075. 

### LINKED ISSUE #3075: Image opengraph tag has double slashes creating an error
### Share your bug report, feature request, or comment.

`og:image` and `og:image:alt` both have the issue.

Example:

image
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnightly.owncast.tv

### PR DESCRIPTION
**Pull request by yk-jp**
The problem was that the frontend automatically changed the server URL by adding `/` at the end.
The path for image tags contained a redundant `/`.
Screenshot 2023-06-13 at 6 44 54 PM

* fixes
`/` is added at the end of the url in advance for prevention. 
Other paths are adjusted accordingly.

TT: #3075

### CODE REVIEW

**Comment by gabek** [comment]
Looks like you accidentally committed `docs/api/index.html`.

**Comment by yk-jp** [comment]
I've reverted the file. Thank you.

**Comment by gabek** [comment]
Thanks so much for working on this @yk-jp! Sorry for the hassle and confusion about the development environment and testing, it's usually simpler, but these specific tags only render in production. Thanks for sticking with it!

**Comment by yk-jp** [comment]
> Thanks so much for working on this @yk-jp! Sorry for the hassle and confusion about the development environment and testing, it's usually simpler, but these specific tags only render in production. Thanks for sticking with it!

No problem! 
I appreciate your quick response!

**Pull request merged**
