### PR TITLE
Give chat a min-height that other elements yield to on mobile clients

### LINKED ISSUE #2595: Android: Page doesn't scroll when keyboard is displayed
### Share your bug report, feature request, or comment.

iOS Safari does the correct thing. When you focus on the text field the page scrolls vertically.

With Android everything stays static and the keyboard covers the page, including chat and the text input.

image

This is what iOS is doing for comparison: 

image

### PR DESCRIPTION
**Pull request by LBBO**
WIP, mostly so others can check out the changes easily.

Fixes #2595

### CODE REVIEW

**Comment by gabek** [comment]
One thing I noticed is a large empty space between the content header and the tab bar:

image

**Comment by LBBO** [comment]
Good catch, thanks! Should be fixed now.

**Comment by gabek** [comment]
This looks and works great! It's doing everything you'd expect it do with regards to the keyboard. And thanks for adding support for passing in class names to some of those components, it's not something I've thought much about, usually I just wrap custom components in a div and give it the class, not the most correct thing to do.

I don't see any reason not to merge it, things look good and this is a big move forward for the mobile layout. I really appreciate all the work you put into it! I look forward to more testing!

**Comment by LBBO** [comment]
Shoot, I should have marked the PR as a draft again since I'm still working on stories for the layout. Should I just open a new PR for them then?

**Comment by gabek** [comment]
Sure, a new PR for stories sounds good!

**Comment by gabek** [comment]
Just as a head's up, I split up the Mobile and Desktop layouts to new files to make it easier to manage, plus it's a first step to making those components not dependent on global state, so stories could be built around them. I did this before looking at #2668.

**Pull request merged**
