### PR TITLE
UI: Make the Admin menu sidebar colors on hover consistent

### LINKED ISSUE #2770: Inconsistent hover colors in admin menu
### Share your bug report, feature request, or comment.

Owncast 0.1.0

The admin menu has some inconsistent hover colors. There is a difference between drop down menu's and single menu items. This looks a bit weird. 

hover

### PR DESCRIPTION
**Pull request by Pranav2612000**
Overwrite the default antd styles to
- Ensure that the icons and the text have the same color ( Previously the icons were blue and text was pink )
- Ensure that the collapsable menu items have the same color as non collapsable items 

Fixes #2770

### CODE REVIEW

**Comment by Pranav2612000** [comment]
image

image

**Comment by gabek** [comment]
This is fantastic, and looks great, thank you! 

I'm curious since you're looking at this, if you could make the icon next to the "Followers" entry (shows up after you enable the social features) to be fixed and work the same way as the other menu items.

image

**Comment by Pranav2612000** [comment]
> This is fantastic, and looks great, thank you!
> 
> I'm curious since you're looking at this, if you could make the icon next to the "Followers" entry (shows up after you enable the social features) to be fixed and work the same way as the other menu items.
> 
> image

On it.

**Comment by Pranav2612000** [comment]
Just found out we're using a .png image for the fediverse icon ( the followers icon ), that's why the color doesn't apply. Will replace that with a svg. Is that fine?

**Comment by gabek** [comment]
Perfect, thanks!

**Comment by Pranav2612000** [comment]
Done. Pushed another commit. How does this look?
image

**Comment by gabek** [comment]
Looks great, thanks so much for taking care of this!

**Pull request merged**
