### PR TITLE
Custom framerate in admin UI

### LINKED ISSUE #3178: Custom Framerate
### Share your bug report, feature request, or comment.

Is there a way to add a custom framerate other than the ones offered? I would like to add 48fps. but I can't find the option anywhere.

### PR DESCRIPTION
**Pull request by janWilejan**
closes #3178

### CODE REVIEW

**Comment by gabek** [comment]
I don't think we should have this. It's very rare it's required and I believe more people will try to take advantage of it and cause problems for themselves than be useful for people.

If in the future enough people really need free form inputs for video settings we can discuss the best way to do that.

**Comment by janWilejan** [comment]
How is changing the frame rate a rare issue? This has come up before ( #1138 ) and the solution then was to add more framerates to the list in the admin UI. 

Streamers should be able to pick any standard broadcast framerate in the UI without needing to make API calls: https://en.wikipedia.org/wiki/List_of_broadcast_video_formats

The UI should
* Encourage selecting a framerate from the list of reasonable defaults
* Warn when using excessive frame rates
* Allow setting any framerate (within a reasonable range)

In what ways do you think people will take advantage of it? Could this be fixed with more / sterner warnings?
image


<blockquote><div><strong><a href="https://en.wikipedia.org/wiki/List_of_broadcast_video_formats">List of broadcast video formats - Wikipedia</a></strong></div></blockquote>

**Comment by gabek** [comment]
Oh I'm not saying changing the framerate is a rare issue, but changing the framrate to a non-standard, custom value is a rare issue. I do think we should have the values for any commonly used framerates, and if a handful of people said 48fps was something they wanted maybe we could add it specifically. But in general I try very hard to not have free form text fields when it comes to values that can have negative impact or allow for typos or bad judgement on the user side.

I tend to use the 80/20 rule with things, though I'm not strict with it. If 80% or more of people would find it useful then it's worth discussing the proper way to add it in a way that is hopefully still easy to use with little room for user error. In this case only one person has ever saked for a non-standard framerate. The issue you referenced was somebody asking for 25/50fps, and that is a standard that I had not thought about previously, so once it was discussed it was added.

I'm certainly not opposed to adding things, but I do think nothing should be quickly added in response to one person. Everything should be useful to most people without just adding more things people have to make choices about.

I hope this makes sense and doesn't come off as me just rejecting changes, but if we made a change for every request everything would be a freeform text field.

**Comment by rmens** [comment]
On a random note; UX wise I like this dropdown more than the current slider.

**Comment by gabek** [comment]
Personally I really like the consistency of the slider. We use it for Latency, CPU utilization, bitrate, and framerate. Just from a mental model standpoint it's nice to have similar ways to select values. Unfortunately the resolution has to be freeform text inputs, but I like how the other values are selected in the same way.

**Pull request closed without merging**
