### PR TITLE
feat(integerations): add route to get user details

### LINKED ISSUE #4015: Create an external version of the user details /api/moderation/chat/user/{userId} API
### Share your bug report, feature request, or comment.

The `/api/moderation/chat/user/{userId}` endpoint appears to not use the same bearer authorization scheme as the other external APIs. The [docs](https://owncast.online/api/latest/#tag/External/operation/GetUserDetails) indicate that you should use a query parameter, and the server will give an error if one isn't provided, but even providing one as described the request always returns a 401 `unauthorized` status. This happens when using both the admin stream key and an integration access token in the query parameter and the bearer auth schemes.

I've tested this and gotten the same behavior on the stable v0.1.3 docker image and the develop branch (421cdd069377fb0473991f6ec23b0a2b2b8be0ad)

### PR DESCRIPTION
**Pull request by varungujarathi9**
Fixes #4015

Steps followed:
- Create contract for the new endpoint in `openapi.yaml` file.
- Ran `gen-api.sh` which made changes in `generated.gen.go` and `generated-types.gen.go`
- Add logic to handlers and downstream functions.
- Tested locally by starting a stream and calling the endpoint using Postman (see images attached)

Screenshot from 2024-11-22 21-19-10
Screenshot from 2024-11-22 21-19-37

Please let me know if `OPTIONS` method should be added to the new endpoint. I tried adding it in the YAML file but it gave an error while running `gen-api.sh`. I can retry if required.

### CODE REVIEW

**Comment by varungujarathi9** [comment]
Hi @gabek 
The failed pull requests are showing these errors: 
```
Get changed files
Unable to locate the commit sha: 8985947d7f0791061506e2b9f4d5a893543d95a7
```

Can this be a CI error? Maybe related to #3999

**Comment by gabek** [comment]
Yeah, the branch currently has to be up-to-date until it's fixed. I pressed the update branch button and all was resolved. Thanks for working on this, I'll be giving it a spin, and we can get it in!

**Comment by gabek** [comment]
Would you mind adding this to the `006_integrations.test.js` integration test?

**Comment by varungujarathi9** [comment]
> Would you mind adding this to the `006_integrations.test.js` integration test?

Done

**Comment by gabek** [comment]
Thank you!

**Pull request merged**
