### PR TITLE
Inline chat moderation UI

### LINKED ISSUE #499: Promote chat participants to moderators
Once the ability to delete chat messages exists, it'd be great to be able to promote other chat participants to moderators so that they can also help delete messages.

This doesn't need to rely on any sort of authentication system, and doesn't need to persist between streams. The minimum viable feature for this would be to give the site admin the ability to give individual chat participants the ability to delete messages.

### LINKED ISSUE #1291: Frontend to allow people to perform moderation actions within chat
Part 2 of https://github.com/owncast/owncast/issues/499

- The backend will support telling a specific user they're now a moderator via the `CONNECTED_USER_INFO` event.
- This should allow a new UI control to show up within chat messages to enable them to remove messages or remove the user.

### PR DESCRIPTION
**Pull request by gingervitis**
Prototype to address https://github.com/owncast/owncast/issues/1291

(Icons indicated in this branch are for temporary purposes )

## Moderator indicators
- Once you have received notice that you are of Moderator status, an icon may appear by your name at the top right.
- An Icon may appear by your name in everybody's message
- You'll will get a system notice that you've achieved moderator status.
- 
image
image

## Moderator actions
As a moderator, when you hover over a message, you could see a `...` menu indicator on each message.
Couple ideas:
- On hover, you'll see the menu icon, and on click you could get a menu of action items. 
image
image

- Or you could be presented with several easy-access options, plus a "more", which will present you some options.
image

### Other "more info" action (WIP)
This would open a small panel in its place that displays that user's detailed info. (in progress)

### CODE REVIEW

**Comment by gabek** [comment]
I'm going to keep building upon this branch to add the moderator functionality.

**Comment by gingervitis** [comment]
Ok here's a first pass at a prototype.


### Moderator indicators
- Once you have received notice that you are of Moderator status, an icon may appear by your name at the top right.
- An Icon may appear by your name in everybody's message
- You'll will get a system notice that you've achieved moderator status.

### Moderator actions
- If you are a moderator, when you hover over a message you will be able to see a menu icon
- Clicking on that icon will present you a quick menu of Ban User or Hide message buttons
- Clicking the "more info" button will display a slightly larger panel of information about that message, including the Sender's previous names, as well the Ban and Hide action buttons.




https://user-images.githubusercontent.com/9563255/132948064-43aff0fe-8be7-4f5a-a2af-c300a9a1dbd8.mov

**Comment by gabek** [comment]
Wired up the UI to support inline moderation actions.

inline-chat-moderation

**Comment by gabek** [comment]
Next up before this can land is to fix the bulk message removal issue that is currently taking place in #1350.

**Pull request merged**
