### PR TITLE
Updating twitter logo to X using logo from Twitter's website

### LINKED ISSUE #3427: Replace Twitter social link icon with the stupid 𝕏 one
### Share your bug report, feature request, or comment.

I guess it has to happen at some point.

### PR DESCRIPTION
**Pull request by jhimanish**
Updating the Twitter Logo to the X logo. The SVG file was taken directly from [Twitter's Brand Toolkit](https://about.twitter.com/en/who-we-are/brand-toolkit). 

Updates summarized:
- Replaced the .svg file in `/web/public/img/platformlogos/twitter.svg`

New Twitter Logo shows up on Storybook: in the Social Platform Images under Frontend Assets:
image

This PR is related to Issue #3427 
Fellow Contributors: @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

### CODE REVIEW

**Comment by gabek** [comment]
Sorry about this, but would you mind reverting the change in `/static/web/img/platformlogos/twitter.svg`? Anything under `/static/web` is automatically generated during web project builds.

I noticed the new logo is much larger than the old one. Does that impact anything when it's used in the Owncast web interface?

**Comment by jhimanish** [comment]
We removed the changes under static/web. I started a test stream with a test video file and added a twitter social handle under the `http://localhost:8080/admin/config/general/` page:
image

When I go back to `localhost:3000`, I can now see the logo shows up normally even though the new logo dimensions are much larger: 
image

However, during this testing, I noticed that the logo on `localhost:8080` is still the old one as seen in the first screenshot. Is this correct behaviour or is there another Twitter logo file that needs to be updated?

**Comment by gabek** [comment]
> However, during this testing, I noticed that the logo on localhost:8080 is still the old one as seen in the first screenshot. Is this correct behaviour or is there another Twitter logo file that needs to be updated?

It's likely just cached. These images don't get changed often so they have a longer cache duration. If you force-refresh your browser, you should see the change.

**Comment by jhimanish** [comment]
I tried force-refreshing the page but the logo on the backed page (localhost:8080) remains as the old twitter logo. 

I tried using npm run build as well to see if it would update the static files but it seemed to have no effect on the twitter logo file. I tried changing the twitter logo in the static/web/ directory manually and this seemed to fixed the issue and displays the updated logo on localhost:8080. 

However, we don't want to modify the static files. Is there a different command I need to run to build the web project to update the static files?

**Comment by gabek** [comment]
Oh! You should be running `npm run dev` and then access `http://localhost:3000`.

**Comment by jhimanish** [comment]
Yes, we are running `npm run dev` and when we access `localhost:3000`, the new logo does show up correctly.

We were just wondering about `localhost:8080` because the updated logo wasn't showing up there from running `go run main.go`

**Comment by gabek** [comment]
Port `8080` is the server component of Owncast. When web changes take place and are merged into `develop`, then a process happens where the web project is built, and copied into the Owncast server at `/static/web`. This only happens after it gets merged in. You won't see non-merged changes at port 8080. For local web development, you hit the development server on `3000`. Hopefully, that clears things up!

**Comment by jhimanish** [comment]
Ah okay, that makes a lot of sense, thank you for clearing that up for us! 

I think this PR should be good to go.

**Comment by gabek** [comment]
Thanks so much for taking care of this!

**Pull request merged**
