### PR TITLE
Renamed rewriteRemotePlaylist

### LINKED ISSUE #3292: Serving Endpoint not used without an S3 backend
### Share your bug report, feature request, or comment.

When you define a custom URL as a serving endpoint in the web interface, it has no affect.

Screenshot 2023-09-04 at 12 05 04
Screenshot 2023-09-04 at 12 05 21

Using the latest stable version 0.1.1 running on Docker

### PR DESCRIPTION
**Pull request by alyx161**

### CODE REVIEW

**Comment by gabek** [comment]
Hey @tfunken, thanks so much for this! Should #3311 stay open, or is this replacing that?

**Comment by alyx161** [comment]
Oh, not sure why I actually made a new PR 😅

But yes, this is the most current one 🙂

**Comment by gabek** [comment]
Thanks, @tfunken! Sorry for the delay in looking at this, I'll be doing so tonight.

**Comment by gabek** [comment]
Works great! Thanks so much for fixing this up, @tfunken! :1st_place_medal:

**Pull request merged**
