### PR TITLE
Center followers list 2515

### LINKED ISSUE #2515: Followers list should be centered in mobile layouts
### Share your bug report, feature request, or comment.

It looks funny being left aligned.

image

### PR DESCRIPTION
**Pull request by ShashwatAgrawal20**
-[x] closes #2515 

image

### CODE REVIEW

**Comment by gabek** [comment]
It seems as if this change centered the items for both desktop and mobile/narrow layouts. The difference here is on desktop it will be able to fit multiple items per row, so left-aligning continues to make sense. But on mobile it'll only be able to fit one per row, so it should be centered as it lays them out in a column.

image

**Comment by ShashwatAgrawal20** [comment]
> It seems as if this change centered the items for both desktop and mobile/narrow layouts. The difference here is on desktop it will be able to fit multiple items per row, so left-aligning continues to make sense. But on mobile it'll only be able to fit one per row, so it should be centered as it lays them out in a column.
> 
> image


yea, sorry my bad I thought it should be centered on all devices.

**Comment by ShashwatAgrawal20** [comment]
hey @gabek added the media query kindly check

**Comment by gabek** [comment]
Awesome, thank you so much! :100:

**Pull request merged**
