### PR TITLE
Follow popup clickable

### LINKED ISSUE #1832: Make notifications popup clickable
Clicking the popup should open the notification modal.

image

### PR DESCRIPTION
**Pull request by t1enne**
Changed the styling of the popup form svg to html elements. Made it interactive.

# Description

Fixes #1832

### CODE REVIEW

**Comment by gabek** [comment]
Yay, works on narrow screens and is clickable now!

Can we get the rounded corners of the popup and the slight border of the notify button back? They looked nice :D

image

**Comment by gabek** [comment]
Whoops, sorry for not being clear in my comment above. When I mentioned the border on the button I meant on the notification button (the bell) not the close button. I'm going to go ahead and merge this in and I'll just make that little tweak. Thank you so much!

**Comment by gabek** [comment]
Doh I had previously tested it on narrow widths and it seemed fine, but now it doesn't.

image

**Comment by t1enne** [comment]
Damn, was sure i committed the z-index change. Will be on my job tomorrow. If you want to, it's just about adding z-index: 100; on the popout.

**Comment by gabek** [comment]
Will do!

**Pull request merged**
