### PR TITLE
chore(go): update to go 1.22

### LINKED ISSUE #3707: Update project to Go 1.22
### Share your bug report, feature request, or comment.

_No response_

### PR DESCRIPTION
**Pull request by gabek**
Updated toolchain references and documentation.

### CODE REVIEW

**Comment by gabek** [comment]
I can't figure out why the API test, run under Earthly, is running under the wrong version of Go.

```
          +api-tests | go: go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)
```

**Comment by mahmed2000** [comment]
Its the docker image for `go-crosscompile:1.22-2024-02-20--f6885c3`. In its [dockerhub image details](https://hub.docker.com/layers/bdwyertech/go-crosscompile/1.22-2024-02-20--f6885c3/images/sha256-c7f8f79204a61e7b4d34b0cc35d8025671f024492b94ad833f17c7b0ebf506f1?context=explore) its set to v1.21.5 instead of v1.22

Image Layer 5 (also in 6):
`ENV GOLANG_VERSION=1.21.5`

**Comment by gabek** [comment]
I didn't even think to not trust the image! I explicitly set the image tag thinking maybe it was using a cached 1.21 image or something. Good catch!

**Comment by gabek** [comment]
Tracking https://github.com/bdwyertech/dkr-go-crosscompile/issues/8. No rush to get this update to 1.22 in. There aren't any features we're relying on or anything.

**Comment by gabek** [comment]
Might as well give this a go!

**Pull request merged**
