### PR TITLE
Support path-based S3 storage. Closes #1495

### LINKED ISSUE #497: Support s3 virtual hosted-style host
Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

The s3-compatible provider I'm using doesn't support path-style

It's easy to make this line configurable:

https://github.com/owncast/owncast/blob/959482e41a306f54ad2a829433613504a8fb4e12/core/storageproviders/s3Storage.go#L179

### LINKED ISSUE #1495: Support path-based S3 storage
Hi!

According to second paragraph of https://owncast.online/docs/storage/, I would to ask for integration with Oracle Cloud Object Storage.

It is compatibile with AWS S3 API, but unfortunatelly except one point:

https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI ->
-> "Modifying your application" ->
-> point 4:

> Use path-based access in your application. Virtual host-style access (accessing a bucket as `bucketname.namespace.compat.objectstorage.region.oraclecloud.com`) **is not supported.**

Thanks!
Artur Angiel

### PR DESCRIPTION
**Pull request by aangiel**
Closes #1495

Revert "Remove forcing old path-style URLs with s3. Closes #497"

This reverts commit b2953028cf6d9040dba2c41268fb3db62260b65a.

How to set up with Oracle Cloud Object Storage (S3 compatibile):

1. Go to `<OWNCAST_URL>/admin/config-storage`
2. Endpoint `https://<NAMESPACE>.compat.objectstorage.<REGION>.oraclecloud.com`
- `<NAMESPACE>` can be retreived from here - `https://cloud.oracle.com/object-storage/buckets`
3. Generate "Access Key" and "Secret Key" - https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI
4. Bucket and Region - bucket name and region (i.e. `eu-frankfurt-1`)
5. Optional Settings -> Serving Endpoint - `https://objectstorage.<REGION>.oraclecloud.com/n/<NAMESPACE>/b/<BUCKET_NAME>/o` - !MUST NOT end with slash '/'!
6. In my case I had to allow Oracle domain in Privacy Badger in Firefox

### CODE REVIEW

**Comment by gabek** [comment]
I should have been more specific, sorry about that. By "switch between the two" I mean have a toggle in the S3 configuration in the admin so you can turn on path-based.  If we hard code path-based then the providers that require host based will break.

**Review by gabek — CHANGES_REQUESTED** [review]
Hard coding a path-based S3 will break providers that only support host-based.

**Comment by aangiel** [comment]
I thought about that I assumed that it's "only" deprecated in AWS, but yes, it can't be like that. I'll try to do that, but I'm not a GoLang and TypeScript coder, so it will be a little bit challenging and fun ;)

**Comment by gabek** [comment]
Feel free to ask if you run into any issues!

**Comment by aangiel** [comment]
Thanks! 

You can watch my mice :D https://stream.angiel.ovh/

<blockquote><div><strong><a href="https://stream.angiel.ovh/">Owncast</a></strong></div></blockquote>

**Review by gabek — APPROVED** [review]

**Comment by gabek** [comment]
Awesome!  Thank you for adding it to the openapi spec as well.

**Comment by aangiel** [comment]
Woah! It was my first Pull Request :D

**Comment by gabek** [comment]
Oh wow, congratulations! Glad it was with Owncast!

**Pull request merged**
