### PR TITLE
little color change in dropdown

### LINKED ISSUE #3800: Admin checkbox item selected has poor legibility
## Steps to replicate
1. log in to admin
2. navigate to Chat & Users > Messages
3. Click on Filter icon
4. Select any checkbox
5. Move mouse away OR click Ok and reopen filter
6. Observe that black text on purple background has poor legibility
image
image

## Expected outcome
Selected item should have a light purple background `background-color: #f5f0ff;` in pages with checkboxes such as the following pages:

- Chat & Users > Messages
- Utilities > Logs

image

### PR DESCRIPTION
**Pull request by joras-droid**
checkbox item selected has poor legibility #3800 

Expected outcome

Selected item should have a light purple background background-color: #f5f0ff; in pages with checkboxes such as the following pages:

    Chat & Users > Messages
    Utilities > Logs

### CODE REVIEW

**Comment by gabek** [comment]
Ignore my previous message, it was for the main web app, not the admin.

**Comment by gabek** [comment]
If you merge `develop` into your PR it should hopefully resolve the CI check. I merged #3832 in.

**Comment by joras-droid** [comment]
@gabek  i think the lint issue have been resolved.

**Comment by gabek** [comment]
@Nirajan1-droid Looks like there's still something. It's stupid that `prettier` doesn't tell you what it is. If you use `prettier` locally, it'll fix it for you. You don't have a newline at the end of the file, so perhaps that's it.

**Comment by joras-droid** [comment]
@gabek i think it is ready now. would you please help to merge into main branch?

**Comment by joras-droid** [comment]
@gabek is it ready , would you please check it

**Comment by gabek** [comment]
Looks great! Thanks so much.

**Pull request merged**
