### PR TITLE
Remove peak viewer counts from public status feed

### LINKED ISSUE #765: Remove overallMaxViewerCount and sessionMaxViewerCount from /api/status
These values used to be used in the web frontend, but they no longer are.  Instead it should only be used in `/api/admin/serverstatus`.

### PR DESCRIPTION
**Pull request by jeyemwey**
Fixes #765.

### CODE REVIEW

**Comment by gabek** [comment]
We should return a a new api response object that doesn't include those two values instead of just setting them to zero.  We have a `adminStatusResponse` so similarly maybe a `webStatusResponse`.

**Comment by jeyemwey** [comment]
`controllers/admin/status.go` uses core.GetStatus to get most of its information, so separating the status models would require to move some functionality to the admin controller instead of just removing it from the core controller.

I can do it later though.

**Comment by gabek** [comment]
There's no need to touch the admin endpoint.  Use `controllers/admin/status.go` as an example.  It gets the status via `core.GetStatus()` and then packages it up in `adminStatusResponse`.  So `controllers/status.go` should get status via `core.GetStatus()` and then package it up in a new `webStatusResponse`, neither of them directly returning `core.GetStatus()` verbatim.

**Comment by jeyemwey** [comment]
Updated, please check if it works out now.

**Comment by gabek** [comment]
Nice, this is great!  Thank you!

**Pull request merged**
