### PR TITLE
fix: #2668 Page Vertical Spacing Issues 

### PR DESCRIPTION
**Pull request by thisprojects**
Should now be working :)

### CODE REVIEW

**Comment by gabek** [comment]
I'm not sure what parts are WIP and what aren't, so I'll just throw out anything that I noticed.

I tried to build the web project so I could access it remotely from mobile devices but it seems like currently the web project won't build with this WIP, so all my testing is done on a desktop browser.

It'll also take a bit to test all the different scenarios and try to figure out how get this running on a device when it doesn't build properly, so it might take me a bit to get full testing feedback. I'll probably be commenting on this PR a few times over the next couple days.

---

Mobile offline: I prefer how it works now to how it used to. Previously the offline state locked the page, but now it doesn't and it's easier to scroll the page to read all the content. Without a player there's no need to lock it. This is nice.

Mobile action button should be inline with the tabs and not create wasted vertical space.
Now:
image

Previously:
image

Mobile action button doesn't do anything anymore:
image

Desktop:

Bottom section looks different than it used to. Spacing and background color are different.
image

**Comment by thisprojects** [comment]
Thanks for the feedback Gabe. I've pushed a few fixes. It should build now, at least it does for me locally. From a WIP point of view, the components still need refactoring and I expect there will be some small(ish) CSS issues - but it should function correctly.

**Comment by gabek** [comment]
It builds now, thank you!

**Comment by gabek** [comment]
The issue where offline mobile without tabs is unscrollable seems to still a problem. 

image

**Comment by gabek** [comment]
The question about what to do about mobile online landscape is still an issue. Offline mobile landscape looks good. image

**Comment by thisprojects** [comment]
> The issue where offline mobile without tabs is unscrollable seems to still a problem.
> 
> image

Thanks Gabe. What are the requirements to get no tabs?

**Comment by thisprojects** [comment]
> The question about what to do about mobile online landscape is still an issue. Offline mobile landscape looks good. 


Not sure what to suggest for landscape. Any ideas? We could detect screen height and give landscape users the desktop experience.

**Comment by thisprojects** [comment]
@gabek The no tab scroll issue on mobile should now be fixed. Can you explain how you go about getting no tabs through the UI? I've just disabled them in the code for testing. 

Also, how should the action buttons behave when there are no tabs? Currently clicking the 3 dot menu does nothing (without tabs), is this expected behaviour?

**Comment by gabek** [comment]
Sorry for all the testing back and forth! Just tested mobile and it looks like all the content has since disappeared.  This is only a problem for offline, however. When the stream is live things pop in and are looking good!

image

**Comment by gabek** [comment]
> @gabek The no tab scroll issue on mobile should now be fixed. Can you explain how you go about getting no tabs through the UI? I've just disabled them in the code for testing.

When you're offline (or chat is disabled), and you don't have social features enabled then the only content available when is the "About" content, so no tabs will show up. This is the default offline state.

> Also, how should the action buttons behave when there are no tabs? Currently clicking the 3 dot menu does nothing (without tabs), is this expected behaviour?

My bad! I fixed the issue yesterday where if there were no tabs the three dot action button wouldn't render, now it will.

**Comment by gabek** [comment]
Oh maybe this is what you were referring to with the menu button. If you merge in the develop branch it'll at least fix the no button issue but this empty menu button is probably just some missing Booleans passed in. 

image

**Comment by thisprojects** [comment]
Thanks Gabe. Have pushed a fix for for the offline "no tabs" issue.

**Comment by gabek** [comment]
Awesome, thank you! I'll do some more testing today and try to resolve those conflicts for you. A bunch of style tweaks went into `develop` and are conflicting with your PR.

**Comment by gabek** [comment]
I merged `develop` into this PR and fixed the conflicts. Functionality still working! I don't think it impacted any of your work, but take a look as a sanity check.

There looks to be a weird z-index thing going on with the chat sidebar where it's covering up modals. I think this is the only issue that I'm really seeing though. Once the tests pass then we can clean up the WIP/commented out stuff in this PR and get it merged into `develop`! Wohoo!

image

**Comment by thisprojects** [comment]
Have fixed Z-index. There were still a few CSS conflicts when rebasing onto develop, did you make changes to the footer?

**Comment by gabek** [comment]
> Have fixed Z-index. There were still a few CSS conflicts when rebasing onto develop, did you make changes to the footer?

Some internal footer styling (padding, font) of the Footer changed, but just small tweaks.

It looks like everything is passing now! I'll do a little more testing today, but is there anything else you can think of that needs to be looked at for these changes? I know there's a bunch of commented out styles in there, but other than that cleanup, do you have anything else you want to look at for these changes?

**Comment by gabek** [comment]
Noticed this in the UI change set. Seems like something changed here where chat is doing something weird in the embed. 

image


https://www.chromatic.com/pullrequest?appId=629132c6e23893003a9e89c5&number=2863&activeElementId=comparison-test-key-631d62bfa0c4f0c1eb500a7b-1200&view=changes

**Comment by thisprojects** [comment]
I'm a bit confused as to what "mode" the diff represents. Looks like online mobile, but without any tabs or stream? Is probably another Z-index issue. How can we reproduce this issue locally?

**Comment by gabek** [comment]
Oh sorry about that. In the link it says "Read-write chat: Example" so it's this Storybook story, the Read-write chat embed:

https://629132c6e23893003a9e89c5-lxybtihwaa.chromatic.com/?path=%2Fstory%2Fowncast-chat-embeds-read-write-chat--example

That UI test also points out a weird gap on the far right, and that is seen in that story as well.


<blockquote><div><strong><a href="https://629132c6e23893003a9e89c5-lxybtihwaa.chromatic.com/?path=%2Fstory%2Fowncast-chat-embeds-read-write-chat--example">Webpack App</a></strong></div></blockquote>

**Comment by thisprojects** [comment]
Thanks Gabe. I've fixed the z-index issue. I think the spacing you mentioned, to the right of the chat, is padding added by storybook (see pic). This may be different from before as the header now uses fixed positioning, which may not be affected by the story book class. Can you explain what the use case is for the chat embed and how the user would go about getting this experience? Ideally I'd like to test it locally. 

Screenshot 2023-04-26 at 15 47 34

**Comment by gabek** [comment]
Oh interesting, the header looks to be pushing out and maybe is the cause for that gap:

image

I compared that to the existing version at https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-embeds-read-write-chat--example:

image


<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-embeds-read-write-chat--example">Webpack App</a></strong></div></blockquote>

**Comment by thisprojects** [comment]
If you check the developer tools when viewing the story and inspect the chat section, you should see that the gap is a result of padding added by (I think) story book. The class is prefixed with sb. Can't be 100% sure without being able to test it manually though.

**Comment by gabek** [comment]
I just tested it myself and the problem isn't there. For reference to test: http://localhost:3000/embed/chat/readwrite/. I'm not sure why the Storybook story is broken in this branch when it's not in `develop`, however. I'll have to find out how to fix it so it'll be accurate.

Once this PR is merged in I'll file all the smaller embed related things separately, like how it doesn't fill the window.

**Comment by thisprojects** [comment]
Cool, thanks Gabe. Are you happy for me to carry out the tidy-up / re-factor and open a proper PR?

**Comment by gabek** [comment]
Absolutely! Thanks so much!

**Comment by thisprojects** [comment]
No problem Gabe, I'll crack on.

**Comment by thisprojects** [comment]
For the time being I've just refactored the action buttons. Should be good to go, there was a merge conflict on last rebase so worth a good check over.

**Comment by gabek** [comment]
Pulling those action buttons out makes sense, thanks for doing that.

Instead of continuing to string this PR along I'm filing individual todos and linking them to here. So that being said, I'm going to merge this in and push forward! Feel free to take a look at any of these individual issues I filed, and I'll be doing the same. But I think we're getting much closer to a fully working web interface!

Thanks so much for all your help on this, all this layout work you put in improved the web interface so much, you're the best. I hope it wasn't too much of a hassle :)

**Pull request merged**
