### PR TITLE
Fixed #2758

### LINKED ISSUE #2758: Download button missing on viewers and CPU usage graph
### Share your bug report, feature request, or comment.

Owncast 0.1.0

In the old Owncast interface, there was a download button to download a graph on the CPU usage page and on the viewers page.

Schermafbeelding 2023-02-28 om 10 34 00

It doesn't show up in the Owncast 0.1.0 nightly.

Schermafbeelding 2023-02-28 om 10 34 43

This is probably a lesser used function. I used it one time to save a graph of a record amount of viewers we had, so it's a nice to have.

### PR DESCRIPTION
**Pull request by bennett1412**
Created a button to download chart generated in admin hardware page.

### CODE REVIEW

**Comment by gabek** [comment]
Weird, I'm not sure what the deal with those conflicts are, but could you take a look so this can be merged in? Thanks!

**Comment by bennett1412** [comment]
my bad, forgot to sync my fork. Have made some updates, should be working now.

**Comment by gabek** [comment]
Totally works as expected! Though the positioning and style of the button is kind of odd. Maybe try giving the button a `ghost` property to remove the borders. And could it be moved out of the way of the actual chart? Maybe more to the upper right?

image

**Comment by bennett1412** [comment]
Is this okay? 
image

**Comment by gabek** [comment]
That looks great, thanks!

**Comment by bennett1412** [comment]
Have pushed the changes

**Comment by gabek** [comment]
Fantastic, looks great! Thanks so much for working on this!

**Comment by bennett1412** [comment]
Thank you for letting me 😁

**Pull request merged**
