### PR TITLE
Cleanup old streaming content when using S3

### PR DESCRIPTION
**Pull request by aangiel**
I've done cleaning of .ts files when using S3 storage, to not to use 10 free gigabytes in Oracle Cloud.

Done a little refactor: 
- made function `CleanupOldContent` in models/storageProvider.go 
- moved `transcoder/hlsFilesystemCleanup.go` to `/storageproviders/local.go` where above function is implemented
- implemented above function in `/storageproviders/s3Storage.go`
- changed the way of invocation

It leaves 50 newest .ts files. I tested it locally with 30 files buffer, but it wasn't sufficient - there were 404s during the stream.

Hope it will be ok :)

### CODE REVIEW

**Comment by gabek** [comment]
I think this makes sense and there's no reason not to have it. Until now we've relied on the auto-expire functionality of the specific S3 providers.

I do kind of wonder why you were getting 404s if there were still 30 available segments, since the HLS playlists shouldn't have nearly that many referenced. While increasing the number I'm sure fixes it, I do worry a little bit about why it happened, since if this happened to somebody else for some reason, with the larger value, they'd be broken.

I'll do some testing with this myself and see if I can see what might be happening.

**Comment by aangiel** [comment]
I'm glad that it was good idea not only for me! 

Now I realized, that I've tested it on my slow laptop with poor internet connection and it was running very bad, so maybe it's the reason? I will test it too on the server with buffer computed like in local storage.

**Comment by gabek** [comment]
As an aside, there are some simple tests in [test/automated/hls](https://github.com/owncast/owncast/tree/develop/test/automated/hls) that you can run against your local instance (setup with `npm install` and run with `npm test`) that will use your local storage config if you have it set.  It's mostly a validation test that the segments that are referenced in the HLS playlist are actually available.

**Comment by gabek** [comment]
I used the HLS test and found anything greater than 13 iterations of checking for validity of segments threw this exception:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb5e2a9]

goroutine 223 [running]:
github.com/owncast/owncast/core/storageproviders.(*S3Storage).sortObjectsByModificationDateDescending.func1(0xc000c88260, 0x0)
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:265 +0x29
sort.medianOfThree_func({0xc000435ee0, 0xc000c88260}, 0xc000cd6f78, 0x0, 0x8)
	/usr/local/go/src/sort/zfuncversion.go:53 +0x4a
sort.doPivot_func({0xc000435ee0, 0xc000c88260}, 0x0, 0x7cf)
	/usr/local/go/src/sort/zfuncversion.go:76 +0x8a
sort.quickSort_func({0xc000435ee0, 0xc000c88260}, 0xc000cd6f78, 0x0, 0xc000435f00)
	/usr/local/go/src/sort/zfuncversion.go:143 +0x85
sort.Slice({0xc91060, 0xc000cd6f78}, 0x800)
	/usr/local/go/src/sort/slice.go:20 +0x9f
github.com/owncast/owncast/core/storageproviders.(*S3Storage).sortObjectsByModificationDateDescending(0xc00018a160, {0xc000cde000, 0x7cf, 0x800})
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:264 +0x7b
github.com/owncast/owncast/core/storageproviders.(*S3Storage).retrieveKeysToDeleteButLeftNewest(0xc000554f88, 0x32)
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:214 +0x5c
github.com/owncast/owncast/core/storageproviders.(*S3Storage).CleanupOldContent(0xc000554fb8, {0x445945, 0xc0007d4100})
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:207 +0x25
github.com/owncast/owncast/core.startOnlineCleanupTimer.func1()
	/home/gabek/src/owncast-develop/core/streamState.go:210 +0x65
```

**Comment by aangiel** [comment]
Sorry for delay. I've corrected it to counting like in local.go and tested on server and works perfectly :)

So it was caused by my slow laptop...

**Comment by gabek** [comment]
This is how I was testing it and ran into issues from `test/automated/hls`.

```
export S3_SECRET=my_s3_secret              ─╯
export S3_REGION=my_s3_region
export S3_ENDPOINT="https://something.digitaloceanspacesorwhatever.com"
export S3_ACCESS_KEY=ABCDEFGACCESSKEY
export S3_BUCKET=your-bucket-name
```

`./run.sh`

Running on `develop` branch runs fine but running this PR results with:

```
 RUNS  ./hls.test.js
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb5e2a9]

goroutine 238 [running]:
github.com/owncast/owncast/core/storageproviders.(*S3Storage).sortObjectsByModificationDateDescending.func1(0xc000a9e160, 0x0)
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:272 +0x29
sort.medianOfThree_func({0xc000415ee0, 0xc000a9e160}, 0xc000bd0948, 0x0, 0x8)
	/usr/local/go/src/sort/zfuncversion.go:53 +0x4a
sort.doPivot_func({0xc000415ee0, 0xc000a9e160}, 0x0, 0x7cf)
	/usr/local/go/src/sort/zfuncversion.go:76 +0x8a
sort.quickSort_func({0xc000415ee0, 0xc000a9e160}, 0xc000bd0948, 0x0, 0xc000415f00)
	/usr/local/go/src/sort/zfuncversion.go:143 +0x85
sort.Slice({0xc91060, 0xc000bd0948}, 0x800)
	/usr/local/go/src/sort/slice.go:20 +0x9f
github.com/owncast/owncast/core/storageproviders.(*S3Storage).sortObjectsByModificationDateDescending(0xc00027a160, {0xc000c02000, 0x7cf, 0x800})
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:271 +0x7b
github.com/owncast/owncast/core/storageproviders.(*S3Storage).retrieveKeysToDeleteButLeftNewest(0xc000558788, 0xd)
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:220 +0x5c
github.com/owncast/owncast/core/storageproviders.(*S3Storage).CleanupOldContent(0xc0005587b8, {0x445945, 0xc0005587d0})
	/home/gabek/src/owncast-develop/core/storageproviders/s3Storage.go:213 +0x2c
github.com/owncast/owncast/core.startOnlineCleanupTimer.func1()
	/home/gabek/src/owncast-develop/core/streamState.go:210 +0x65
 FAIL  ./hls.test.js (54.013 s)wncast/core.startOnlineCleanupTimer
  fetch and parse HLS
    ✓ fetch master playlist (24 ms)
    ✓ verify there is a media playlist (1 ms)
    ✓ verify there are segments (304 ms)
    ✓ fetch and monitor media playlist segments 0 (3630 ms)
    ✓ fetch and monitor media playlist segments 1 (3599 ms)
    ✓ fetch and monitor media playlist segments 2 (3586 ms)
    ✓ fetch and monitor media playlist segments 3 (3602 ms)
    ✓ fetch and monitor media playlist segments 4 (3607 ms)
    ✓ fetch and monitor media playlist segments 5 (3617 ms)
    ✓ fetch and monitor media playlist segments 6 (3646 ms)
    ✓ fetch and monitor media playlist segments 7 (3582 ms)
    ✓ fetch and monitor media playlist segments 8 (3628 ms)
    ✓ fetch and monitor media playlist segments 9 (3580 ms)
    ✓ fetch and monitor media playlist segments 10 (3652 ms)
    ✓ fetch and monitor media playlist segments 11 (3663 ms)
    ✕ fetch and monitor media playlist segments 12 (3311 ms)
    ✕ fetch and monitor media playlist segments 13 (3303 ms)
    ✕ fetch and monitor media playlist segments 14 (3302 ms)
```

**Comment by aangiel** [comment]
@gabek - sorry for delay, I'll try to check it next week.

**Pull request closed without merging**
