### PR TITLE
remove global variables from core/storageproviders

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gabek** [comment]
Could you provide some background on why you're proposing these changes?

**Comment by ghost** [comment]
Related to #1439, I am concerned about the amount of global state that is used throughout the source code. I believe it is in the best interest of stability and memory safety that the amount package-wide variables be reduced and converted to struct fields with locking, where appropriate.

**Comment by gabek** [comment]
These changes make sense since things like the uploader is specific to s3 logic and not to the storageprovider package as a whole, so architecturally it shouldn't be available to other logic in the package.  Thank you!

**Comment by gabek** [comment]
Thanks again for cleaning this up.  Just did some testing and all looks good.

**Pull request merged**
