### PR TITLE
Markdown-Editor-LineWrapping

### LINKED ISSUE #3870: Feature request: enable word wrap on the Markdown editor
### Share your bug report, feature request, or comment.

The Markdown editor used for things like the offline message and the custom page content can be incredibly difficult to work with due to the lack of word wrapping. It would be really nice if I could actually see all of what I'm writing on a longer paragraph.

image

### PR DESCRIPTION
**Pull request by zockicookie**
Implemented LineWrapping for both Markdown-Editors in the General-Tab of the Configuration-Page. This has been done using CodeMirrors built in LineWrapping-Extension.

image

### CODE REVIEW

**Comment by zockicookie** [comment]
@gabek some checks are not passing. Is there something corrupted within my fork? Do you want me to change something?

**Comment by gabek** [comment]
Something is up, sorry about that! I filed something for me to look into it. https://github.com/owncast/owncast/issues/3909. I'll test your PR soon and we'll get it in, thanks for your help!

**Comment by zockicookie** [comment]
@gabek alright then, thank you for your work. Let me know if you need something!

**Comment by gabek** [comment]
This is great, thank you! How do you feel about enabling line wrapping for the CSS and Javascript code editors as well?

**Comment by zockicookie** [comment]
@gabek I would gladly take this on as well. Since I am new to the project, though: Would you be so kind and open a new issue where you roughly describe the location of the editors? You can assign it to me then and I will try my best.

**Comment by gabek** [comment]
Oh, it's the same thing that you've already done, but they're located on the `General` admin page under Scripting and Appearance.

**Comment by zockicookie** [comment]
Alright, I found them, thank you. I will just go ahead and do this real quick.

**Comment by zockicookie** [comment]
Done!

**Comment by gabek** [comment]
Awesome, thank you so much!

**Pull request merged**
