### PR TITLE
Change Airplay to SVG and refactor

### LINKED ISSUE #2011: Player: AirPlay icon cannot be colorized
The AirPlay icon, because it's a PNG, does not take the color of the rest of the icons in the player. I'm assuming switching to a SVG should fix this.

### PR DESCRIPTION
**Pull request by aprilthepink**
I changed the Airplay PNG to a public domain SVG from Wikimedia. I also refactored VideoJS.scss to propper SCSS syntax while doing that :)

Closes #2011

### CODE REVIEW

**Comment by aprilthepink** [comment]
Oh yea I don't own a iFruit device so I can't check if its displayed properly :eyes:

**Comment by gabek** [comment]
I'll check it out on my iPhone today, thank you for doing this!

**Comment by gabek** [comment]
It looks like the sizing of the icon image is a little off.

image

**Comment by aprilthepink** [comment]
thanks I am gonna work on this!

**Comment by aprilthepink** [comment]
hope this fixed it. made its size 50% as I estimated thats the size used here

**Comment by gabek** [comment]
Looks like it's the same. If you want to test it yourself just comment out the conditional at line 160 so the button will show up for you. https://github.com/owncast/owncast/blob/webv2/web/components/video/OwncastPlayer/OwncastPlayer.tsx#L160-L183

image


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/OwncastPlayer.tsx at webv2 · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/OwncastPlayer.tsx at webv2 · owncast/owncast</div></blockquote>

**Comment by aprilthepink** [comment]
What happened to thw pip logo on ,our i pad lmao

**Comment by gabek** [comment]
That last screenshot was from Brave running on Linux.

**Comment by gabek** [comment]
I'll test this on an actual Apple device soon! Thank you!

**Comment by gabek** [comment]
The size looks great, but it seems like some style change now made it the wrong color.

image

**Comment by aprilthepink** [comment]
> The size looks great, but it seems like some style change now made it the wrong color.
> 
> image

I did not encounter that issue while testing :/
can you make sure its not device related?

**Comment by gabek** [comment]
Good news! On Safari (desktop) the color is correct. I'll eventually have to figure out what's going on with iOS.  Thanks for working on this!

image

**Pull request merged**
