### PR TITLE
fixing grammar

### PR DESCRIPTION
**Pull request by G2G2G2G**
I guess California no speak english

### CODE REVIEW

**Comment by gabek** [comment]
Please elaborate.

**Comment by G2G2G2G** [comment]
On what? Is English your first language?

**Comment by G2G2G2G** [comment]
scanning subtitles on youtube you can note at least one other guy has noticed it too lmfao
29:46

https://www.youtube.com/watch?v=8r6_QPkh-34

<blockquote><div> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=8r6_QPkh-34">Owncast - Self-Hosted Streaming & Chat</a></strong></div><div>Looking for a self-hosted Twitch alternative with live video streaming and chat room functionality? Join me for a look at Owncast, a turn-key solution with f...</div></blockquote>

**Comment by gabek** [comment]
Please grow up. This isn't a place for trolling.

**Pull request merged**
