### PR TITLE
Validate nodeinfo response by schema

### LINKED ISSUE #1925: Add nodeinfo validation to automated tests
We should use the schema (for example [nodeinfo.diaspora.software/ns/schema/2.0](https://nodeinfo.diaspora.software/ns/schema/2.0)) to verify the validity of the owncast's response. 

Good news: Currently it is returning a valid response!

### PR DESCRIPTION
**Pull request by MFTabriz**
…and
- remove ` stable` from `actions/setup-go@v3` steps’ input
- improve config management API tests (check default value of all config parameters and verify change in their reported states through API calls)
- add basic federation API tests
- log the errors and warnings of `npm install` for automated API tests setup

closes #1925 (properly!)

### CODE REVIEW

**Comment by gabek** [comment]
Since you're more passionate about nodeinfo than anybody else I know (somebody has to be!) I have a completely tangential question for you.

Currently I say that this server has 1 user, since I treat the streamer as the user, and that's the only user represented on the Fediverse. However I don't know if that's in the spirit of what the "user" count is, and I'm wondering if I should count the _chat_ users as a more accurate representation of the usage of the server. What do you think?

**Comment by MFTabriz** [comment]
> Since you're more passionate about nodeinfo than anybody else I know (somebody has to be!) I have a completely tangential question for you.
> 
> Currently I say that this server has 1 user, since I treat the streamer as the user, and that's the only user represented on the Fediverse. However I don't know if that's in the spirit of what the "user" count is, and I'm wondering if I should count the _chat_ users as a more accurate representation of the usage of the server. What do you think?

I’d say the current behaviour is correct. That should only report the fediverse users which other servers can interact with.

**Comment by gabek** [comment]
> improve config management API tests

If you could keep these changes to a minimum, or if they're new tests, put them in a different file, that would make life easier for me since I have a branch with a bunch of changes due to a rework of stream keys/admin passwords, so if I could minimize the amount of time I'm wading through merge conflicts of tests that would be awesome.

> log the output of npm install for automated API tests setup

Do we have to? I run these tests a lot locally and npm spews the console full of useless crap and makes it harder to scroll through the test results.

**Comment by MFTabriz** [comment]
> > improve config management API tests
> 
> If you could keep these changes to a minimum, or if they're new tests, put them in a different file, that would make life easier for me since I have a branch with a bunch of changes due to a rework of stream keys/admin passwords, so if I could minimize the amount of time I'm wading through merge conflicts of tests that would be awesome.

I’ll definitely clean up the config management tests and move some of them to separate files. Also, if you tell me the name of your branch, I can open another PR to adapt all of its tests.

> > log the output of npm install for automated API tests setup
> 
> Do we have to? I run these tests a lot locally and npm spews the console full of useless crap and makes it harder to scroll through the test results.

Originally even the errors were suppressed. I changed the log level to warnings now. I can also disable the progress bar if it’s also annoying.

**Comment by MFTabriz** [comment]
I think I should stop the changes and wait for a review.
 
Please point me to other branches where this PR must be merged but it may have conflicts.

**Comment by gabek** [comment]
I have a branch up with the stream key changes at `gek/additional-streamkeys` if you're interested in tweaking you PR to support that.

**Comment by MFTabriz** [comment]
> 



> I have a branch up with the stream key changes at `gek/additional-streamkeys` if you're interested in tweaking you PR to support that.

I opened  #2390 for that branch.

**Comment by MFTabriz** [comment]
@gabek If there’s not going to be any release from the develop branch in future, I think we can close this PR. webv2 branch has all of these (and even more) tests

**Pull request closed without merging**
