### PR TITLE
feat: add translations support to admin pages and components

### PR DESCRIPTION
**Pull request by SufyaanKhateeb**
Related to Issue #3950
Added translations support for admin main page and its components, help page, handware-info page. Added translations support for LogTable, NewsFeed and StreamHealthOverview components.

### CODE REVIEW

**Comment by gabek** [comment]
This is awesome! I gave it a spin, but I received some errors with the log table. I can't imagine it has anything to do with translation (you never know, though), but I wasn't getting the same error with `develop`. So I'll have to see what's going on.

**Comment by gabek** [comment]
Could you merge `develop` into this branch? I noticed `LogTable` is missing a change that was made recently.

**Comment by SufyaanKhateeb** [comment]
There are a lot of differences between the localization branch and the develop branch. I have merged the develop branch into my branch, if you want I can revert the changes as there are a lot of them. The issue on the Log Table has been resolved, it was hooks calling order issue.

**Comment by gabek** [comment]
I merged the `localization` branch into your PR.

**Comment by SufyaanKhateeb** [comment]
@gabek thanks for merging the localization branch, I didn't see that my localization branch was behind. 
What is the acceptance criteria for the PR?

**Comment by gabek** [comment]
We're good to go! Thanks so much for working on this! 🥇

**Pull request merged**
