### PR TITLE
feat: add support for robots.txt disabling search indexing

### LINKED ISSUE #2684: Option to prevent Google indexing of Owncast pages
### Feature request

An experimental instance of mine got indexed by Google. Currently the web interface doesn't prevent indexing by search engines. 

I propose a checkbox in the admin interface that reads "Prevent search engines from indexing this Owncast instance". It could be unchecked by default. When it's checked, the following could be placed in the `<head>` of the public web app.

`<meta name="robots" content="noindex, nofollow">`

If the checkbox is not checked, the following could be placed:

`<meta name="robots" content="index, nofollow">`

#### Making the case for nofollow
Since most Owncast interfaces provide a chat interface that let's the public enter anything, it's good practice to tell search engines to not follow external links on the page. Because nofollow links do not pass PageRank they don't impact search engine rankings and this prevents spammers for trying to boost their SEO juice via popular Owncast instances.

### PR DESCRIPTION
**Pull request by gabek**
Can toggle disabling search engine indexing via `robot.txt` directives. Closes #2684

### CODE REVIEW

**Comment by rmens** [comment]
Hi Gabe, any reason you chose the robots.txt route and not the metatags? This covers the 'don't index this instance' scenario, but doesn't add any metatags that encourage search engines to index the site.

**Comment by gabek** [comment]
The number of things that require server side rendered page content the better. There's currently no guarantee that the meta tags would be rendered for a search bot without Javascript. `robots.txt` is server rendered, and therefore always available because it doesn't require javascript. If somebody flips the switch to disable search engine indexing I don't want it to be a "maybe, depending on the search engine".

As far as I've been able to tell Owncast instances have been indexed without problems so far, so the real change here is to tell search engines not to index it like. If explicit `Allow` directives for some reason are needed they can be added, but I don't believe they have to be.

**Comment by rmens** [comment]
Makes sense. I wasn't aware that the metatags were client side rendered (being a simple PHP/MySQL guy 😌).

**Comment by gabek** [comment]
Such is the drawback of completely client-side rendered pages! Technically a part of the build step performs an optimization where it will render static HTML instead of Javascript components for items it believes should be static and in-lined, but it's up to the compiler to make that call so there's no guarantee that HTML will exist before Javascript kicks in. It usually doesn't matter much, but in this case it would.

**Pull request merged**
