### PR TITLE
Chat popup

### LINKED ISSUE #2848: pop-out chat button
It will be nice to have a pop-up chat button on the stream page

I know pop-up chat already exist in the form of the embed read-write chat but putting a button at the bottom of the chat or on the rolling menu at the top on the stream page is way more user-frendly (and as a user, you don't have to go dig into the documentation to even know it is possible to have one. And even then, it's not really user-frendly imo to modify the URL to have that function)

like as a user, i use it a lot on twitch to put the chat on another screen and have the video feed in fullscreen on another screen

### PR DESCRIPTION
**Pull request by janWilejan**
~~TODO: changing your name in the popup isn't reflected in the main interface yet~~

Closes #2848

### CODE REVIEW

**Comment by gabek** [comment]
@janWilejan Would you mind commenting on #2848 so it can be assigned to you?

**Comment by gabek** [comment]
Awesome, thanks so much for picking this up! I have a couple thoughts that might make it a little less confusing for people.

- If you access `/embed/chat/readwrite/` directly the Pop out chat option is available in the menu. That should probably be hidden in that case.
- The "Hide chat" option is available on the pop out window. That should probably be hidden when the pop out window is available since the main chat is automatically hidden once you pop out the window.

**Comment by janWilejan** [comment]
hm... looking through the codebase, i'm seeing a lot of booleans which exist mostly to affect the status of the chat. (`chatAvailable`, `chatDisabled`, `online`, `chatToggleVisible`, and a few needed to make popups work). these should probably be consolidated into an enum somewhere:

```
enum ChatStatus {
  OFFLINE, // Stream is not playing or chat is disabled
  ACTIVE, // Chat is open (the default state when the stream is online)
  HIDDEN, // User has chat hidden
  POPPED_OUT, // User has chat playing in a popout window
  EMBEDDED, // Chat is opened at /embed/chat/readwrite/
}
```

are there any variants missing?

**Comment by gabek** [comment]
Yeah! Some of those are derived selectors that are already generating chat state based on the status of different things. You can see them here: https://github.com/owncast/owncast/blob/develop/web/components/stores/ClientConfigStore.tsx#L116-L155

We could absolutely add to those selectors or improve them to include additional logic.

You can find the core application state (offline, online, loading, goodbye) (goodbye state is the 5 minutes after a stream ends that chat should still be available) at https://github.com/owncast/owncast/blob/develop/web/components/stores/application-state.ts#L31-L57.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/web/components/stores/ClientConfigStore.tsx at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/web/components/stores/ClientConfigStore.tsx at develop · owncast/owncast</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/web/components/stores/application-state.ts at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/web/components/stores/application-state.ts at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
This is awesome! It looks to be working great. Thanks for adding that enum. :1st_place_medal:

**Pull request merged**
