### PR TITLE
Footer text wrap solved.

### LINKED ISSUE #2504: Footer wraps on narrow desktop layouts (like iPad)
On narrow desktop layouts the footer wraps and looks odd. Maybe it needs to decrease the font size more as the viewport narrows to fit it all.

image

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR closes the following issue:
closes #2504 

### Changes made:
- Font size reduced from `0.8rem` to `10px`.

### Screenshots:
owncast

### CODE REVIEW

**Comment by Rishav1707** [comment]
@gabek  Please run the workflow awaiting approval

**Comment by gabek** [comment]
While this technically solves the tablet issue, you changed the font for all layouts so it looks quite small on desktop layouts now.

Could you either:

1. Make the font scale proportionally as the viewport width shrinks?
2. Or set a breakpoint to reduce the font size at a specific width?

image

**Comment by Rishav1707** [comment]
> While this technically solves the tablet issue, you changed the font for all layouts so it looks quite small on desktop layouts now.
> 
> Could you either:
> 
> 1. Make the font scale proportionally as the viewport width shrinks?
> 2. Or set a breakpoint to reduce the font size at a specific width?
> 
> image

Done @gabek

**Comment by gabek** [comment]
Awesome! Thank you! :+1:

**Comment by Rishav1707** [comment]
> Awesome! Thank you! 👍

Your welcome @gabek

**Pull request merged**
