### PR TITLE
Increase outbound worker pool size to use follower count

### LINKED ISSUE #3811: Admin Social links UI not reflecting modifications
### Share your bug report, feature request, or comment.

When I **add**, **edit**, **delete**, and **reorder** a social link, the UI is not updated immediately with revised data. I have to refresh the page to view the revised data.

## Expected behaviour
All kinds of edits should be updated in real time.

## Steps to replicate (add a social link)

1. Navigate to Configuration -> General
2. Click 'Add a new social link' Button
3. Enter https://directory.owncast.online/
4. Click 'Ok'
5. Observe button changes to loading state, link is not added to list

image

6. Click 'Cancel'
7. Refresh page
8. Observe Link is added to list

image

<hr>
Note: Something might be affecting the UI stuff as there's issue #3229 

Should the user be able to add a social link without a name?

### PR DESCRIPTION
**Pull request by gabek**
@mahmed2000 I made this change based on your recommendation to bump this up. It'll only calculate this number at app launch, but it should be good enough for most cases, to be in the right ballpark due to the the multiplier.

Re: #4009

### CODE REVIEW

**Comment by mahmed2000** [comment]
This will bump both the queue size and the number of goroutines handling outbox activities. I'm not sure what the downstream consequences of that might be (if any) by spawning that many. What I was considering was more just the queue specifically, because of the original issue, but this should help too since its still mostly just waiting on http requests than hogging computation. It was more a case of handling bursts than keeping a proportional throughput.

Does this still work if the `GetFollowerCount` call returns 0 followers? It would spawn 0 workers in that case, and make it impossible to follow the server since follow accepts never get sent. Might be better to use the number of followers for the max size and the old number of processors for a blanket minimum.

**Comment by gabek** [comment]
> Does this still work if the GetFollowerCount call returns 0 followers? It would spawn 0 workers in that case, and make it impossible to follow the server since follow accepts never get sent.

I actually set a minimum number of `50` followers (arbitrary value), so even if there are zero, or few followers, the number of available workers should be enough.

https://github.com/owncast/owncast/pull/4049/files#diff-193ff8009eaca18502f2a9974a3da62b5fc00f6fbf55215229c80594bb4c84cfR45

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/owncast/owncast/pull/4049">Increase outbound worker pool size to use follower count by gabek · Pull Request #4049 · owncast/owncast</a></strong></div><div>@mahmed2000 I made this change based on your recommendation to bump this up. It&#39;ll only calculate this number at app launch, but it should be good enough for most cases, to be in the right ball...</div></blockquote>

**Comment by mahmed2000** [comment]
> I actually set a minimum number of 50 followers

I see that now, brain somehow glossed over the Max call. This should be good then, outside of the other issue of decoupling federation updates from the API calls.

Does the buffering issue you mentioned in the original PR thread still occur?

**Comment by gabek** [comment]
> Does the buffering issue you mentioned in the original PR thread still occur?

Unfortunately, nightly only gets updated with the nightly build, and it's all automated. So to perform the exact same test, I'd have to merge this in. So I guess I'll do that and test that and the API call performance.

**Comment by gabek** [comment]
This change did improve a couple of things.

- No more buffering just from simple playback.
- When adding tags or social links the UI successfully updates.

However, buffering does occur briefly when saving any of those pieces of server metadata that cue up ActivityPub activities, probably as expected. I wonder if throttling would help at all. Probably not, as in this test case there aren't actually that many followers.

**Comment by mahmed2000** [comment]
Tried a local test again for video. The latency on segments doesn't seem to be affected by either setting tags or spamming in a bunch of new follows mid-stream in any meaningful level of variance. Might be something only over latency connections, might not. I did see #3189, so it probably is apub related in some way.

**Comment by gabek** [comment]
There are two different issues. One is ActivityPub related. Any type of application blocking that is taking place when queuing up outbound ActivityPub activities. The second is the DDoS the server receives by the Fediverse all hitting the Owncast server. This also happens if you simply share the link to the Fediverse. This isn't ActivityPub related. I'm tracking this issue here: #4020.

And I think you're right, you probably didn't see any issue due to latency and general stability. In the real world there are timeouts and stuff going on with all these ActivityPub connections happening to servers that might be down, or broken or whatever. (I also think this machine is probably more resource constrained haha)

But #3189 is still completely reproducible and it's probably time to add some instrumentation around it.

**Review by danhendo89 — APPROVED** [review]

**Pull request merged**
